# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\slavd\Documents\GitHub\simGUI\gui\my_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 737)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabVehicle = QtWidgets.QWidget()
        self.tabVehicle.setObjectName("tabVehicle")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tabVehicle)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frameVehicle = QtWidgets.QFrame(self.tabVehicle)
        self.frameVehicle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVehicle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVehicle.setObjectName("frameVehicle")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameVehicle)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frameImg = QtWidgets.QFrame(self.frameVehicle)
        self.frameImg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameImg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameImg.setObjectName("frameImg")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameImg)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelVehicleImg = QtWidgets.QLabel(self.frameImg)
        self.labelVehicleImg.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVehicleImg.sizePolicy().hasHeightForWidth())
        self.labelVehicleImg.setSizePolicy(sizePolicy)
        self.labelVehicleImg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelVehicleImg.setText("")
        self.labelVehicleImg.setPixmap(QtGui.QPixmap(":/Vehicles/M113.jpg"))
        self.labelVehicleImg.setScaledContents(False)
        self.labelVehicleImg.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVehicleImg.setWordWrap(False)
        self.labelVehicleImg.setOpenExternalLinks(False)
        self.labelVehicleImg.setObjectName("labelVehicleImg")
        self.verticalLayout_8.addWidget(self.labelVehicleImg)
        self.verticalLayout_7.addWidget(self.frameImg)
        self.frameVehicleType = QtWidgets.QFrame(self.frameVehicle)
        self.frameVehicleType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frameVehicleType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameVehicleType.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameVehicleType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVehicleType.setObjectName("frameVehicleType")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameVehicleType)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelVehicleType = QtWidgets.QLabel(self.frameVehicleType)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVehicleType.setFont(font)
        self.labelVehicleType.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVehicleType.setObjectName("labelVehicleType")
        self.verticalLayout.addWidget(self.labelVehicleType)
        self.comboBoxVehicleType = QtWidgets.QComboBox(self.frameVehicleType)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxVehicleType.setFont(font)
        self.comboBoxVehicleType.setObjectName("comboBoxVehicleType")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.verticalLayout.addWidget(self.comboBoxVehicleType)
        self.checkBoxDifferential = QtWidgets.QCheckBox(self.frameVehicleType)
        self.checkBoxDifferential.setObjectName("checkBoxDifferential")
        self.verticalLayout.addWidget(self.checkBoxDifferential)
        self.verticalLayout_7.addWidget(self.frameVehicleType)
        self.verticalLayout_12.addWidget(self.frameVehicle)
        self.tabWidget.addTab(self.tabVehicle, "")
        self.tabTerrain = QtWidgets.QWidget()
        self.tabTerrain.setObjectName("tabTerrain")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tabTerrain)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frameTerrain = QtWidgets.QFrame(self.tabTerrain)
        self.frameTerrain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrain.setObjectName("frameTerrain")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameTerrain)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frameTerrainType = QtWidgets.QFrame(self.frameTerrain)
        self.frameTerrainType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainType.setObjectName("frameTerrainType")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameTerrainType)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelTerrainType = QtWidgets.QLabel(self.frameTerrainType)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTerrainType.setFont(font)
        self.labelTerrainType.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTerrainType.setObjectName("labelTerrainType")
        self.verticalLayout_3.addWidget(self.labelTerrainType)
        self.frameTerrainTypeOptions = QtWidgets.QFrame(self.frameTerrainType)
        self.frameTerrainTypeOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainTypeOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainTypeOptions.setObjectName("frameTerrainTypeOptions")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameTerrainTypeOptions)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameTerrainTypeChoice = QtWidgets.QFrame(self.frameTerrainTypeOptions)
        self.frameTerrainTypeChoice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainTypeChoice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainTypeChoice.setObjectName("frameTerrainTypeChoice")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frameTerrainTypeChoice)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioBtnRoad = QtWidgets.QRadioButton(self.frameTerrainTypeChoice)
        self.radioBtnRoad.setChecked(True)
        self.radioBtnRoad.setObjectName("radioBtnRoad")
        self.verticalLayout_9.addWidget(self.radioBtnRoad)
        self.radioBtnSoil = QtWidgets.QRadioButton(self.frameTerrainTypeChoice)
        self.radioBtnSoil.setObjectName("radioBtnSoil")
        self.verticalLayout_9.addWidget(self.radioBtnSoil)
        self.horizontalLayout.addWidget(self.frameTerrainTypeChoice)
        self.frameTerrainTypeParams = QtWidgets.QFrame(self.frameTerrainTypeOptions)
        self.frameTerrainTypeParams.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainTypeParams.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainTypeParams.setObjectName("frameTerrainTypeParams")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameTerrainTypeParams)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelTerrainTypeOptions = QtWidgets.QLabel(self.frameTerrainTypeParams)
        self.labelTerrainTypeOptions.setObjectName("labelTerrainTypeOptions")
        self.verticalLayout_2.addWidget(self.labelTerrainTypeOptions)
        self.comboBoxTerrainTypeOptions = QtWidgets.QComboBox(self.frameTerrainTypeParams)
        self.comboBoxTerrainTypeOptions.setObjectName("comboBoxTerrainTypeOptions")
        self.comboBoxTerrainTypeOptions.addItem("")
        self.comboBoxTerrainTypeOptions.addItem("")
        self.comboBoxTerrainTypeOptions.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxTerrainTypeOptions)
        self.labelParams = QtWidgets.QLabel(self.frameTerrainTypeParams)
        self.labelParams.setObjectName("labelParams")
        self.verticalLayout_2.addWidget(self.labelParams)
        self.labelTerrainParams = QtWidgets.QLabel(self.frameTerrainTypeParams)
        self.labelTerrainParams.setObjectName("labelTerrainParams")
        self.verticalLayout_2.addWidget(self.labelTerrainParams)
        self.horizontalLayout.addWidget(self.frameTerrainTypeParams)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frameTerrainTypeOptions)
        self.verticalLayout_10.addWidget(self.frameTerrainType)
        self.frameTerrainProfile = QtWidgets.QFrame(self.frameTerrain)
        self.frameTerrainProfile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainProfile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainProfile.setObjectName("frameTerrainProfile")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameTerrainProfile)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelTerrainProfile = QtWidgets.QLabel(self.frameTerrainProfile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTerrainProfile.setFont(font)
        self.labelTerrainProfile.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTerrainProfile.setObjectName("labelTerrainProfile")
        self.verticalLayout_6.addWidget(self.labelTerrainProfile)
        self.frameTerrainProfileOptions = QtWidgets.QFrame(self.frameTerrainProfile)
        self.frameTerrainProfileOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainProfileOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainProfileOptions.setObjectName("frameTerrainProfileOptions")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameTerrainProfileOptions)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameTerrainProfileType = QtWidgets.QFrame(self.frameTerrainProfileOptions)
        self.frameTerrainProfileType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainProfileType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainProfileType.setObjectName("frameTerrainProfileType")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameTerrainProfileType)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelProfileType = QtWidgets.QLabel(self.frameTerrainProfileType)
        self.labelProfileType.setObjectName("labelProfileType")
        self.verticalLayout_5.addWidget(self.labelProfileType)
        self.comboBoxTerrainProfileType = QtWidgets.QComboBox(self.frameTerrainProfileType)
        self.comboBoxTerrainProfileType.setObjectName("comboBoxTerrainProfileType")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.verticalLayout_5.addWidget(self.comboBoxTerrainProfileType)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frameTerrainProfileType)
        self.frameTerrainProfileParams = QtWidgets.QFrame(self.frameTerrainProfileOptions)
        self.frameTerrainProfileParams.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainProfileParams.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainProfileParams.setObjectName("frameTerrainProfileParams")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameTerrainProfileParams)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelHeight = QtWidgets.QLabel(self.frameTerrainProfileParams)
        self.labelHeight.setObjectName("labelHeight")
        self.verticalLayout_4.addWidget(self.labelHeight)
        self.doubleSpinBoxHeight = QtWidgets.QDoubleSpinBox(self.frameTerrainProfileParams)
        self.doubleSpinBoxHeight.setObjectName("doubleSpinBoxHeight")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxHeight)
        self.sliderHeight = QtWidgets.QSlider(self.frameTerrainProfileParams)
        self.sliderHeight.setMinimum(-10)
        self.sliderHeight.setMaximum(10)
        self.sliderHeight.setOrientation(QtCore.Qt.Horizontal)
        self.sliderHeight.setObjectName("sliderHeight")
        self.verticalLayout_4.addWidget(self.sliderHeight)
        self.labelDistance = QtWidgets.QLabel(self.frameTerrainProfileParams)
        self.labelDistance.setObjectName("labelDistance")
        self.verticalLayout_4.addWidget(self.labelDistance)
        self.doubleSpinBoxDistance = QtWidgets.QDoubleSpinBox(self.frameTerrainProfileParams)
        self.doubleSpinBoxDistance.setObjectName("doubleSpinBoxDistance")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxDistance)
        self.slideDistance = QtWidgets.QSlider(self.frameTerrainProfileParams)
        self.slideDistance.setOrientation(QtCore.Qt.Horizontal)
        self.slideDistance.setObjectName("slideDistance")
        self.verticalLayout_4.addWidget(self.slideDistance)
        self.labelAngle = QtWidgets.QLabel(self.frameTerrainProfileParams)
        self.labelAngle.setObjectName("labelAngle")
        self.verticalLayout_4.addWidget(self.labelAngle)
        self.spinBoxSlopeAngle = QtWidgets.QSpinBox(self.frameTerrainProfileParams)
        self.spinBoxSlopeAngle.setObjectName("spinBoxSlopeAngle")
        self.verticalLayout_4.addWidget(self.spinBoxSlopeAngle)
        self.sliderSlope = QtWidgets.QSlider(self.frameTerrainProfileParams)
        self.sliderSlope.setMinimum(-45)
        self.sliderSlope.setMaximum(45)
        self.sliderSlope.setSingleStep(5)
        self.sliderSlope.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSlope.setObjectName("sliderSlope")
        self.verticalLayout_4.addWidget(self.sliderSlope)
        self.horizontalLayout_2.addWidget(self.frameTerrainProfileParams)
        self.verticalLayout_6.addWidget(self.frameTerrainProfileOptions)
        self.verticalLayout_10.addWidget(self.frameTerrainProfile)
        self.verticalLayout_13.addWidget(self.frameTerrain)
        self.tabWidget.addTab(self.tabTerrain, "")
        self.tabVelocity = QtWidgets.QWidget()
        self.tabVelocity.setObjectName("tabVelocity")
        self.frameVel = QtWidgets.QFrame(self.tabVelocity)
        self.frameVel.setGeometry(QtCore.QRect(20, 20, 651, 151))
        self.frameVel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVel.setObjectName("frameVel")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frameVel)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.labelVelProfile = QtWidgets.QLabel(self.frameVel)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVelProfile.setFont(font)
        self.labelVelProfile.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVelProfile.setObjectName("labelVelProfile")
        self.verticalLayout_15.addWidget(self.labelVelProfile)
        self.frameVelOptions = QtWidgets.QFrame(self.frameVel)
        self.frameVelOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVelOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVelOptions.setObjectName("frameVelOptions")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frameVelOptions)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.labelSetVel = QtWidgets.QLabel(self.frameVelOptions)
        self.labelSetVel.setObjectName("labelSetVel")
        self.verticalLayout_14.addWidget(self.labelSetVel)
        self.spinBoxVel = QtWidgets.QSpinBox(self.frameVelOptions)
        self.spinBoxVel.setMinimum(5)
        self.spinBoxVel.setMaximum(100)
        self.spinBoxVel.setProperty("value", 25)
        self.spinBoxVel.setObjectName("spinBoxVel")
        self.verticalLayout_14.addWidget(self.spinBoxVel)
        self.sliderVel = QtWidgets.QSlider(self.frameVelOptions)
        self.sliderVel.setMinimum(5)
        self.sliderVel.setMaximum(100)
        self.sliderVel.setProperty("value", 25)
        self.sliderVel.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVel.setObjectName("sliderVel")
        self.verticalLayout_14.addWidget(self.sliderVel)
        self.verticalLayout_15.addWidget(self.frameVelOptions)
        self.tabWidget.addTab(self.tabVelocity, "")
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.radiobtnShowVid = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobtnShowVid.setObjectName("radiobtnShowVid")
        self.verticalLayout_11.addWidget(self.radiobtnShowVid)
        self.pushbtnRunSim = QtWidgets.QPushButton(self.centralwidget)
        self.pushbtnRunSim.setObjectName("pushbtnRunSim")
        self.verticalLayout_11.addWidget(self.pushbtnRunSim)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_11.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenResults = QtWidgets.QAction(MainWindow)
        self.actionOpenResults.setObjectName("actionOpenResults")
        self.menuFile.addAction(self.actionOpenResults)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxVehicleType.highlighted['QString'].connect(self.labelVehicleImg.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelVehicleType.setText(_translate("MainWindow", "Vehicle Type"))
        self.comboBoxVehicleType.setItemText(0, _translate("MainWindow", "M113"))
        self.comboBoxVehicleType.setItemText(1, _translate("MainWindow", "Eitan"))
        self.comboBoxVehicleType.setItemText(2, _translate("MainWindow", "Namer"))
        self.comboBoxVehicleType.setItemText(3, _translate("MainWindow", "Merkava"))
        self.comboBoxVehicleType.setItemText(4, _translate("MainWindow", "Merkava (With Spikes)"))
        self.checkBoxDifferential.setText(_translate("MainWindow", "Simulate Differential"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVehicle), _translate("MainWindow", "Vehicle"))
        self.labelTerrainType.setText(_translate("MainWindow", "Terrain Type"))
        self.radioBtnRoad.setText(_translate("MainWindow", "Road"))
        self.radioBtnSoil.setText(_translate("MainWindow", "Soil"))
        self.labelTerrainTypeOptions.setText(_translate("MainWindow", "Options:"))
        self.comboBoxTerrainTypeOptions.setItemText(0, _translate("MainWindow", "Sand"))
        self.comboBoxTerrainTypeOptions.setItemText(1, _translate("MainWindow", "LETE Sand"))
        self.comboBoxTerrainTypeOptions.setItemText(2, _translate("MainWindow", "Clay"))
        self.labelParams.setText(_translate("MainWindow", "Params:"))
        self.labelTerrainParams.setText(_translate("MainWindow", "mu = 1 | blah = 2"))
        self.labelTerrainProfile.setText(_translate("MainWindow", "Terrain Profile"))
        self.labelProfileType.setText(_translate("MainWindow", "Profile Type:"))
        self.comboBoxTerrainProfileType.setItemText(0, _translate("MainWindow", "Flat"))
        self.comboBoxTerrainProfileType.setItemText(1, _translate("MainWindow", "Step"))
        self.comboBoxTerrainProfileType.setItemText(2, _translate("MainWindow", "Slope"))
        self.labelHeight.setText(_translate("MainWindow", "Height:"))
        self.labelDistance.setText(_translate("MainWindow", "Distance From Vehicle:"))
        self.labelAngle.setText(_translate("MainWindow", "Slope Angle:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTerrain), _translate("MainWindow", "Terrain"))
        self.labelVelProfile.setText(_translate("MainWindow", "Velocity Profile"))
        self.labelSetVel.setText(_translate("MainWindow", "Set Maximum Velocity:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVelocity), _translate("MainWindow", "Velocity Profile"))
        self.radiobtnShowVid.setText(_translate("MainWindow", "Show Video"))
        self.pushbtnRunSim.setText(_translate("MainWindow", "Run Simulation"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpenResults.setText(_translate("MainWindow", "Open Results"))
import resources.resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
