# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\slavd\Documents\GitHub\simGUI\gui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabVehicle = QtWidgets.QWidget()
        self.tabVehicle.setObjectName("tabVehicle")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tabVehicle)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frameVehicle = QtWidgets.QFrame(self.tabVehicle)
        self.frameVehicle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVehicle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVehicle.setObjectName("frameVehicle")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameVehicle)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frameImg = QtWidgets.QFrame(self.frameVehicle)
        self.frameImg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameImg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameImg.setObjectName("frameImg")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameImg)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelVehicleImg = QtWidgets.QLabel(self.frameImg)
        self.labelVehicleImg.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVehicleImg.sizePolicy().hasHeightForWidth())
        self.labelVehicleImg.setSizePolicy(sizePolicy)
        self.labelVehicleImg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelVehicleImg.setText("")
        self.labelVehicleImg.setPixmap(QtGui.QPixmap(":/Vehicles/M113.jpg"))
        self.labelVehicleImg.setScaledContents(False)
        self.labelVehicleImg.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVehicleImg.setWordWrap(False)
        self.labelVehicleImg.setOpenExternalLinks(False)
        self.labelVehicleImg.setObjectName("labelVehicleImg")
        self.verticalLayout_8.addWidget(self.labelVehicleImg)
        self.verticalLayout_7.addWidget(self.frameImg)
        self.frameVehicleType = QtWidgets.QFrame(self.frameVehicle)
        self.frameVehicleType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frameVehicleType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameVehicleType.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameVehicleType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVehicleType.setObjectName("frameVehicleType")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameVehicleType)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelVehicleType = QtWidgets.QLabel(self.frameVehicleType)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVehicleType.setFont(font)
        self.labelVehicleType.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVehicleType.setObjectName("labelVehicleType")
        self.verticalLayout.addWidget(self.labelVehicleType)
        self.comboBoxVehicleType = QtWidgets.QComboBox(self.frameVehicleType)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxVehicleType.setFont(font)
        self.comboBoxVehicleType.setObjectName("comboBoxVehicleType")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.comboBoxVehicleType.addItem("")
        self.verticalLayout.addWidget(self.comboBoxVehicleType)
        self.checkBoxDifferential = QtWidgets.QCheckBox(self.frameVehicleType)
        self.checkBoxDifferential.setObjectName("checkBoxDifferential")
        self.verticalLayout.addWidget(self.checkBoxDifferential)
        self.verticalLayout_7.addWidget(self.frameVehicleType)
        self.verticalLayout_12.addWidget(self.frameVehicle)
        self.tabWidget.addTab(self.tabVehicle, "")
        self.tabTerrain = QtWidgets.QWidget()
        self.tabTerrain.setObjectName("tabTerrain")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tabTerrain)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frameTerrain = QtWidgets.QFrame(self.tabTerrain)
        self.frameTerrain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrain.setObjectName("frameTerrain")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frameTerrain)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frameTerrainType = QtWidgets.QFrame(self.frameTerrain)
        self.frameTerrainType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainType.setObjectName("frameTerrainType")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frameTerrainType)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.labelTerrainProp = QtWidgets.QLabel(self.frameTerrainType)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTerrainProp.setFont(font)
        self.labelTerrainProp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTerrainProp.setObjectName("labelTerrainProp")
        self.verticalLayout_19.addWidget(self.labelTerrainProp)
        self.frameProps = QtWidgets.QFrame(self.frameTerrainType)
        self.frameProps.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProps.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProps.setObjectName("frameProps")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameProps)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameTerrainPropsParams = QtWidgets.QFrame(self.frameProps)
        self.frameTerrainPropsParams.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainPropsParams.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainPropsParams.setObjectName("frameTerrainPropsParams")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameTerrainPropsParams)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameTerrainTypeChoice = QtWidgets.QFrame(self.frameTerrainPropsParams)
        self.frameTerrainTypeChoice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainTypeChoice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainTypeChoice.setObjectName("frameTerrainTypeChoice")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frameTerrainTypeChoice)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioBtnRoad = QtWidgets.QRadioButton(self.frameTerrainTypeChoice)
        self.radioBtnRoad.setChecked(True)
        self.radioBtnRoad.setObjectName("radioBtnRoad")
        self.verticalLayout_9.addWidget(self.radioBtnRoad)
        self.radioBtnSoil = QtWidgets.QRadioButton(self.frameTerrainTypeChoice)
        self.radioBtnSoil.setObjectName("radioBtnSoil")
        self.verticalLayout_9.addWidget(self.radioBtnSoil)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frameTerrainTypeChoice)
        self.frameTerrainTypeParams = QtWidgets.QFrame(self.frameTerrainPropsParams)
        self.frameTerrainTypeParams.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainTypeParams.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainTypeParams.setObjectName("frameTerrainTypeParams")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameTerrainTypeParams)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelParams = QtWidgets.QLabel(self.frameTerrainTypeParams)
        self.labelParams.setObjectName("labelParams")
        self.verticalLayout_2.addWidget(self.labelParams)
        self.labelTerrainPropParams = QtWidgets.QLabel(self.frameTerrainTypeParams)
        self.labelTerrainPropParams.setObjectName("labelTerrainPropParams")
        self.verticalLayout_2.addWidget(self.labelTerrainPropParams)
        self.labelTerrainSoilType = QtWidgets.QLabel(self.frameTerrainTypeParams)
        self.labelTerrainSoilType.setObjectName("labelTerrainSoilType")
        self.verticalLayout_2.addWidget(self.labelTerrainSoilType)
        self.comboBoxTerrainPropsSoilType = QtWidgets.QComboBox(self.frameTerrainTypeParams)
        self.comboBoxTerrainPropsSoilType.setObjectName("comboBoxTerrainPropsSoilType")
        self.comboBoxTerrainPropsSoilType.addItem("")
        self.comboBoxTerrainPropsSoilType.addItem("")
        self.comboBoxTerrainPropsSoilType.addItem("")
        self.comboBoxTerrainPropsSoilType.addItem("")
        self.comboBoxTerrainPropsSoilType.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxTerrainPropsSoilType)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.frameTerrainTypeParams)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.frameTerrainPropsParams)
        self.frameTerrainPropsGeneral = QtWidgets.QFrame(self.frameProps)
        self.frameTerrainPropsGeneral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainPropsGeneral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainPropsGeneral.setObjectName("frameTerrainPropsGeneral")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameTerrainPropsGeneral)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelStartPoint = QtWidgets.QLabel(self.frameTerrainPropsGeneral)
        self.labelStartPoint.setObjectName("labelStartPoint")
        self.verticalLayout_5.addWidget(self.labelStartPoint)
        self.spinBox_StartPoint = QtWidgets.QSpinBox(self.frameTerrainPropsGeneral)
        self.spinBox_StartPoint.setMinimum(-100)
        self.spinBox_StartPoint.setMaximum(100)
        self.spinBox_StartPoint.setSingleStep(10)
        self.spinBox_StartPoint.setProperty("value", -10)
        self.spinBox_StartPoint.setObjectName("spinBox_StartPoint")
        self.verticalLayout_5.addWidget(self.spinBox_StartPoint)
        self.slider_StartPoint = QtWidgets.QSlider(self.frameTerrainPropsGeneral)
        self.slider_StartPoint.setMinimum(-100)
        self.slider_StartPoint.setMaximum(100)
        self.slider_StartPoint.setSingleStep(10)
        self.slider_StartPoint.setProperty("value", -10)
        self.slider_StartPoint.setOrientation(QtCore.Qt.Horizontal)
        self.slider_StartPoint.setInvertedAppearance(False)
        self.slider_StartPoint.setObjectName("slider_StartPoint")
        self.verticalLayout_5.addWidget(self.slider_StartPoint)
        self.labelEndPoint = QtWidgets.QLabel(self.frameTerrainPropsGeneral)
        self.labelEndPoint.setObjectName("labelEndPoint")
        self.verticalLayout_5.addWidget(self.labelEndPoint)
        self.spinBox_EndPoint = QtWidgets.QSpinBox(self.frameTerrainPropsGeneral)
        self.spinBox_EndPoint.setMinimum(100)
        self.spinBox_EndPoint.setMaximum(10000)
        self.spinBox_EndPoint.setSingleStep(100)
        self.spinBox_EndPoint.setProperty("value", 600)
        self.spinBox_EndPoint.setObjectName("spinBox_EndPoint")
        self.verticalLayout_5.addWidget(self.spinBox_EndPoint)
        self.slider_EndPoint = QtWidgets.QSlider(self.frameTerrainPropsGeneral)
        self.slider_EndPoint.setMinimum(100)
        self.slider_EndPoint.setMaximum(10000)
        self.slider_EndPoint.setSingleStep(100)
        self.slider_EndPoint.setProperty("value", 600)
        self.slider_EndPoint.setOrientation(QtCore.Qt.Horizontal)
        self.slider_EndPoint.setObjectName("slider_EndPoint")
        self.verticalLayout_5.addWidget(self.slider_EndPoint)
        self.labelOffset = QtWidgets.QLabel(self.frameTerrainPropsGeneral)
        self.labelOffset.setObjectName("labelOffset")
        self.verticalLayout_5.addWidget(self.labelOffset)
        self.doubleSpinBox_Offset = QtWidgets.QDoubleSpinBox(self.frameTerrainPropsGeneral)
        self.doubleSpinBox_Offset.setDecimals(1)
        self.doubleSpinBox_Offset.setMinimum(-1.0)
        self.doubleSpinBox_Offset.setMaximum(1.0)
        self.doubleSpinBox_Offset.setSingleStep(0.1)
        self.doubleSpinBox_Offset.setProperty("value", -0.9)
        self.doubleSpinBox_Offset.setObjectName("doubleSpinBox_Offset")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_Offset)
        self.slider_Offset = QtWidgets.QSlider(self.frameTerrainPropsGeneral)
        self.slider_Offset.setMinimum(-10)
        self.slider_Offset.setMaximum(10)
        self.slider_Offset.setSingleStep(1)
        self.slider_Offset.setProperty("value", -9)
        self.slider_Offset.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Offset.setObjectName("slider_Offset")
        self.verticalLayout_5.addWidget(self.slider_Offset)
        self.horizontalLayout_2.addWidget(self.frameTerrainPropsGeneral)
        self.verticalLayout_19.addWidget(self.frameProps)
        self.verticalLayout_21.addWidget(self.frameTerrainType)
        self.frameTerrainProfile = QtWidgets.QFrame(self.frameTerrain)
        self.frameTerrainProfile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainProfile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainProfile.setObjectName("frameTerrainProfile")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameTerrainProfile)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelTerrainProfile = QtWidgets.QLabel(self.frameTerrainProfile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTerrainProfile.setFont(font)
        self.labelTerrainProfile.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTerrainProfile.setObjectName("labelTerrainProfile")
        self.verticalLayout_6.addWidget(self.labelTerrainProfile)
        self.frameTerrainProfileOptions = QtWidgets.QFrame(self.frameTerrainProfile)
        self.frameTerrainProfileOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainProfileOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainProfileOptions.setObjectName("frameTerrainProfileOptions")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameTerrainProfileOptions)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frameTerrainProfileType = QtWidgets.QFrame(self.frameTerrainProfileOptions)
        self.frameTerrainProfileType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerrainProfileType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTerrainProfileType.setObjectName("frameTerrainProfileType")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameTerrainProfileType)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_2 = QtWidgets.QFrame(self.frameTerrainProfileType)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelProfileType = QtWidgets.QLabel(self.frame_2)
        self.labelProfileType.setObjectName("labelProfileType")
        self.verticalLayout_3.addWidget(self.labelProfileType)
        self.comboBoxTerrainProfileType = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxTerrainProfileType.setObjectName("comboBoxTerrainProfileType")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.comboBoxTerrainProfileType.addItem("")
        self.verticalLayout_3.addWidget(self.comboBoxTerrainProfileType)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.horizontalLayout_3.addWidget(self.frameTerrainProfileType)
        self.frame_3 = QtWidgets.QFrame(self.frameTerrainProfileOptions)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.labelTerrainCustom_1 = QtWidgets.QLabel(self.frame_3)
        self.labelTerrainCustom_1.setObjectName("labelTerrainCustom_1")
        self.verticalLayout_4.addWidget(self.labelTerrainCustom_1)
        self.doubleSpinBoxTerrainCustom_1 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxTerrainCustom_1.setDecimals(1)
        self.doubleSpinBoxTerrainCustom_1.setMinimum(-1.0)
        self.doubleSpinBoxTerrainCustom_1.setMaximum(1.0)
        self.doubleSpinBoxTerrainCustom_1.setSingleStep(0.1)
        self.doubleSpinBoxTerrainCustom_1.setObjectName("doubleSpinBoxTerrainCustom_1")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxTerrainCustom_1)
        self.labelTerrainCustom_2 = QtWidgets.QLabel(self.frame_3)
        self.labelTerrainCustom_2.setObjectName("labelTerrainCustom_2")
        self.verticalLayout_4.addWidget(self.labelTerrainCustom_2)
        self.doubleSpinBoxTerrainCustom_2 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxTerrainCustom_2.setDecimals(1)
        self.doubleSpinBoxTerrainCustom_2.setMinimum(-1.0)
        self.doubleSpinBoxTerrainCustom_2.setMaximum(1.0)
        self.doubleSpinBoxTerrainCustom_2.setSingleStep(0.1)
        self.doubleSpinBoxTerrainCustom_2.setObjectName("doubleSpinBoxTerrainCustom_2")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxTerrainCustom_2)
        self.labelTerrainCustom_3 = QtWidgets.QLabel(self.frame_3)
        self.labelTerrainCustom_3.setObjectName("labelTerrainCustom_3")
        self.verticalLayout_4.addWidget(self.labelTerrainCustom_3)
        self.doubleSpinBoxTerrainCustom_3 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxTerrainCustom_3.setDecimals(1)
        self.doubleSpinBoxTerrainCustom_3.setMinimum(-1.0)
        self.doubleSpinBoxTerrainCustom_3.setMaximum(1.0)
        self.doubleSpinBoxTerrainCustom_3.setSingleStep(0.1)
        self.doubleSpinBoxTerrainCustom_3.setObjectName("doubleSpinBoxTerrainCustom_3")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxTerrainCustom_3)
        self.labelTerrainCustom_4 = QtWidgets.QLabel(self.frame_3)
        self.labelTerrainCustom_4.setObjectName("labelTerrainCustom_4")
        self.verticalLayout_4.addWidget(self.labelTerrainCustom_4)
        self.doubleSpinBoxTerrainCustom_4 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxTerrainCustom_4.setDecimals(1)
        self.doubleSpinBoxTerrainCustom_4.setMinimum(-1.0)
        self.doubleSpinBoxTerrainCustom_4.setMaximum(1.0)
        self.doubleSpinBoxTerrainCustom_4.setSingleStep(0.1)
        self.doubleSpinBoxTerrainCustom_4.setObjectName("doubleSpinBoxTerrainCustom_4")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxTerrainCustom_4)
        self.labelTerrainCustom_5 = QtWidgets.QLabel(self.frame_3)
        self.labelTerrainCustom_5.setObjectName("labelTerrainCustom_5")
        self.verticalLayout_4.addWidget(self.labelTerrainCustom_5)
        self.doubleSpinBoxTerrainCustom_5 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxTerrainCustom_5.setDecimals(1)
        self.doubleSpinBoxTerrainCustom_5.setMinimum(-1.0)
        self.doubleSpinBoxTerrainCustom_5.setMaximum(1.0)
        self.doubleSpinBoxTerrainCustom_5.setSingleStep(0.1)
        self.doubleSpinBoxTerrainCustom_5.setObjectName("doubleSpinBoxTerrainCustom_5")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxTerrainCustom_5)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_6.addWidget(self.frameTerrainProfileOptions)
        self.verticalLayout_21.addWidget(self.frameTerrainProfile)
        self.verticalLayout_13.addWidget(self.frameTerrain)
        self.tabWidget.addTab(self.tabTerrain, "")
        self.tabVelocity = QtWidgets.QWidget()
        self.tabVelocity.setObjectName("tabVelocity")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tabVelocity)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frameVel = QtWidgets.QFrame(self.tabVelocity)
        self.frameVel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVel.setObjectName("frameVel")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frameVel)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.labelVelProfile = QtWidgets.QLabel(self.frameVel)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVelProfile.setFont(font)
        self.labelVelProfile.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVelProfile.setObjectName("labelVelProfile")
        self.verticalLayout_15.addWidget(self.labelVelProfile)
        self.frameVelOptions = QtWidgets.QFrame(self.frameVel)
        self.frameVelOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVelOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVelOptions.setObjectName("frameVelOptions")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frameVelOptions)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.labelSetVel = QtWidgets.QLabel(self.frameVelOptions)
        self.labelSetVel.setObjectName("labelSetVel")
        self.verticalLayout_14.addWidget(self.labelSetVel)
        self.spinBox_Vel = QtWidgets.QSpinBox(self.frameVelOptions)
        self.spinBox_Vel.setMinimum(5)
        self.spinBox_Vel.setMaximum(100)
        self.spinBox_Vel.setProperty("value", 25)
        self.spinBox_Vel.setObjectName("spinBox_Vel")
        self.verticalLayout_14.addWidget(self.spinBox_Vel)
        self.slider_Vel = QtWidgets.QSlider(self.frameVelOptions)
        self.slider_Vel.setMinimum(5)
        self.slider_Vel.setMaximum(100)
        self.slider_Vel.setProperty("value", 25)
        self.slider_Vel.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Vel.setObjectName("slider_Vel")
        self.verticalLayout_14.addWidget(self.slider_Vel)
        self.verticalLayout_15.addWidget(self.frameVelOptions)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.verticalLayout_18.addWidget(self.frameVel)
        self.tabWidget.addTab(self.tabVelocity, "")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frameGeneral = QtWidgets.QFrame(self.tabGeneral)
        self.frameGeneral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneral.setObjectName("frameGeneral")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frameGeneral)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frameSimTime = QtWidgets.QFrame(self.frameGeneral)
        self.frameSimTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSimTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSimTime.setObjectName("frameSimTime")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frameSimTime)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.labelVelProfile_2 = QtWidgets.QLabel(self.frameSimTime)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelVelProfile_2.setFont(font)
        self.labelVelProfile_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVelProfile_2.setObjectName("labelVelProfile_2")
        self.verticalLayout_16.addWidget(self.labelVelProfile_2)
        self.labelSimTime = QtWidgets.QLabel(self.frameSimTime)
        self.labelSimTime.setObjectName("labelSimTime")
        self.verticalLayout_16.addWidget(self.labelSimTime)
        self.spinBox_SimTime = QtWidgets.QSpinBox(self.frameSimTime)
        self.spinBox_SimTime.setMinimum(0)
        self.spinBox_SimTime.setSingleStep(1)
        self.spinBox_SimTime.setProperty("value", 40)
        self.spinBox_SimTime.setObjectName("spinBox_SimTime")
        self.verticalLayout_16.addWidget(self.spinBox_SimTime)
        self.slider_SimTime = QtWidgets.QSlider(self.frameSimTime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_SimTime.sizePolicy().hasHeightForWidth())
        self.slider_SimTime.setSizePolicy(sizePolicy)
        self.slider_SimTime.setMinimum(10)
        self.slider_SimTime.setMaximum(100)
        self.slider_SimTime.setProperty("value", 40)
        self.slider_SimTime.setOrientation(QtCore.Qt.Horizontal)
        self.slider_SimTime.setObjectName("slider_SimTime")
        self.verticalLayout_16.addWidget(self.slider_SimTime)
        self.verticalLayout_17.addWidget(self.frameSimTime)
        spacerItem6 = QtWidgets.QSpacerItem(20, 414, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem6)
        self.verticalLayout_20.addWidget(self.frameGeneral)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.pushbtnRunSim = QtWidgets.QPushButton(self.centralwidget)
        self.pushbtnRunSim.setObjectName("pushbtnRunSim")
        self.verticalLayout_11.addWidget(self.pushbtnRunSim)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenResults = QtWidgets.QAction(MainWindow)
        self.actionOpenResults.setObjectName("actionOpenResults")
        self.menuFile.addAction(self.actionOpenResults)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxVehicleType.highlighted['QString'].connect(self.labelVehicleImg.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelVehicleType.setText(_translate("MainWindow", "Vehicle Type"))
        self.comboBoxVehicleType.setItemText(0, _translate("MainWindow", "M113"))
        self.comboBoxVehicleType.setItemText(1, _translate("MainWindow", "Namer"))
        self.comboBoxVehicleType.setItemText(2, _translate("MainWindow", "Eitan"))
        self.comboBoxVehicleType.setItemText(3, _translate("MainWindow", "Merkava"))
        self.comboBoxVehicleType.setItemText(4, _translate("MainWindow", "Merkava (With Spikes)"))
        self.checkBoxDifferential.setText(_translate("MainWindow", "Simulate Differential"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVehicle), _translate("MainWindow", "Vehicle"))
        self.labelTerrainProp.setText(_translate("MainWindow", "Terrain Properties"))
        self.radioBtnRoad.setText(_translate("MainWindow", "Road"))
        self.radioBtnSoil.setText(_translate("MainWindow", "Soil"))
        self.labelParams.setText(_translate("MainWindow", "Params:"))
        self.labelTerrainPropParams.setText(_translate("MainWindow", "init"))
        self.labelTerrainSoilType.setText(_translate("MainWindow", "Soil Type:"))
        self.comboBoxTerrainPropsSoilType.setItemText(0, _translate("MainWindow", "Default"))
        self.comboBoxTerrainPropsSoilType.setItemText(1, _translate("MainWindow", "Dry Sand"))
        self.comboBoxTerrainPropsSoilType.setItemText(2, _translate("MainWindow", "Megiddo_B"))
        self.comboBoxTerrainPropsSoilType.setItemText(3, _translate("MainWindow", "LETE Sand"))
        self.comboBoxTerrainPropsSoilType.setItemText(4, _translate("MainWindow", "Heavy Clay W.E.S"))
        self.labelStartPoint.setText(_translate("MainWindow", "Start Point:"))
        self.labelEndPoint.setText(_translate("MainWindow", "End Point:"))
        self.labelOffset.setText(_translate("MainWindow", "Z Offset:"))
        self.labelTerrainProfile.setText(_translate("MainWindow", "Terrain Profile"))
        self.labelProfileType.setText(_translate("MainWindow", "Profile Type:"))
        self.comboBoxTerrainProfileType.setItemText(0, _translate("MainWindow", "Flat"))
        self.comboBoxTerrainProfileType.setItemText(1, _translate("MainWindow", "Step"))
        self.comboBoxTerrainProfileType.setItemText(2, _translate("MainWindow", "Slope"))
        self.comboBoxTerrainProfileType.setItemText(3, _translate("MainWindow", "Slope and Step"))
        self.comboBoxTerrainProfileType.setItemText(4, _translate("MainWindow", "Sinus"))
        self.comboBoxTerrainProfileType.setItemText(5, _translate("MainWindow", "Gaussian"))
        self.comboBoxTerrainProfileType.setItemText(6, _translate("MainWindow", "Random"))
        self.label_2.setText(_translate("MainWindow", "Options:"))
        self.labelTerrainCustom_1.setText(_translate("MainWindow", "Label 1:"))
        self.labelTerrainCustom_2.setText(_translate("MainWindow", "Label 2:"))
        self.labelTerrainCustom_3.setText(_translate("MainWindow", "Label 3:"))
        self.labelTerrainCustom_4.setText(_translate("MainWindow", "Label 4:"))
        self.labelTerrainCustom_5.setText(_translate("MainWindow", "Label 5:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTerrain), _translate("MainWindow", "Terrain"))
        self.labelVelProfile.setText(_translate("MainWindow", "Velocity Profile"))
        self.labelSetVel.setText(_translate("MainWindow", "Set Maximum Velocity:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVelocity), _translate("MainWindow", "Velocity Profile"))
        self.labelVelProfile_2.setText(_translate("MainWindow", "Simulation Settings"))
        self.labelSimTime.setText(_translate("MainWindow", "Set Simulation Time:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("MainWindow", "General"))
        self.pushbtnRunSim.setText(_translate("MainWindow", "Run Simulation"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpenResults.setText(_translate("MainWindow", "Open Results"))
import gui.resources.resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
